config/routes.rb
Rails.application.routes.draw do
  get 'for_homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  root 'homes#index'
  get 'forhomes', to: 'forhomes#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/for_homes_controller.rb
class ForHomesController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/for_homes_helper.rb
module ForHomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/for_homes/index.html.erb
<div style="background-color:#C38D9E">
<h1><center>Home</center></h1>
<h2>About College</h2>
<hr><p>Shri Jayantilal Hirachand Sanghvi Gujarati Innovative College Of Commerce and Science is a new branch of Shri Gujarati Samaj, a highly dedicated and renowned social organization of the city. Gujarati Samaj Education Society established S.J.H.S.I.C.C.S College in 2006, which is an important identity belonging to the Gujarati Samaj Indore.
SJHS Gujarati Innovative College Of Commerce and Science is located in the prime location of Indore, near Bombay hospital with large campus.Established in 1951, P.M.B. Gujarati Commerce College is a premier institute located in Indore, Madhya Pradesh. The institute offers Degree and Diploma courses including UG and PG programs. These programs are offered in Full-Time mode. Candidate can pursue multiple ranges of courses like M.Com, B.Com, PG Diploma in the stream of Accounting & Commerce, Science. Over the period, P.M.B. Gujarati Commerce College has gained expertise through its trained and experienced faculty in the fields of Computer Science. P.M.B. Gujarati Commerce College offers courses distributed over 60 seats in total. The institute provides good facilities all around the campus, such as Auditorium, Cafeteria, Gym, Hospital / Medical Facilities, Hostel, Labs, Library, Sports Complex, etc.
Particulars	Statistics
Campus Location	Indore, Madhya Pradesh
Courses Offered	UG and PG
No. of Seats	60
Median Salary	
Fees Range.	
</p>
<hr>
<h2>What Is Event :-</h2>
<p>An event can be described as a public assembly for the purpose of celebration, education, marketing or reunion. Events can be classified on the basis of their size, type and context.
An event can be: Events like a birthday party, hen/stag party, graduation day, bachelor's party, engagement, wedding, anniversary, retirement day, funeral, etc. Education and career events
Events like education fair, job fair, workshop, seminar, debate, contest, competition etc.
Another critical factor in the success of an event is the creation of a unique and engaging experience for attendees. The event should be designed in a way that appeals to the target audience and creates a lasting impression. This can be achieved through various means such as the selection of the venue, entertainment, and activities, as well as the overall theme and atmosphere of the event. Event planning also involves careful consideration of the logistics and operations required to execute the event. This includes the selection of the appropriate venue, transportation, accommodations, and catering services. It also involves the management of risks and contingency planning to mitigate any potential issues or disruptions that may arise.
 </p>
<img src= "https://e7.pngegg.com/pngimages/511/100/png-clipart-illustration-crowd-illustration-businessman-flattening-element-photography-service.png" width="1300" height="200">
</div>

app/views/homes/index.html.erb
<div  style="background-color:#83677B">
<h2><center>SHRI K.B PATEL GUJARATI COLLEGE INDORE</center></h2>
<h2><center>COLLEGE-FEST</center></h2>
<center><%= link_to 'Home' ,  for_homes_index_path, style: 'color:black;' %></center><br>
<center>Student Registration</center><br>
<i><h3>EVENTS :--</h3></i>
<p><b>An event can be defined as a planned or unplanned occurrence, situation, or incident that has significance or meaning. It can range from small personal events such as a birthday party to large-scale global events such as the Olympic Games or a natural disaster. The planning and execution of an event involve a wide range of activities such as budgeting, marketing, logistics, and coordination. Depending on the size and complexity of the event, it may require a team of professionals with specialized skills and expertise to ensure its success. One of the key elements of a successful event is effective communication. Clear communication is essential throughout the planning and execution stages to ensure that all stakeholders are informed and aligned with the goals and objectives of the event. This includes communication with suppliers, vendors, sponsors, attendees, and other stakeholders.
</b></p>
<img src="https://st3.depositphotos.com/1037987/14046/i/450/depositphotos_140469690-stock-photo-friends-cheering-up-toast.jpg" width="300" height="250">&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://www.planteriagroup.com/wp-content/uploads/2020/01/108_xNewsThumbResizex481.jpg" width="300" height="250">&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://d12m9erqbesehq.cloudfront.net/wp-content/uploads/sites/2/2023/11/12193749/Types-of-social-events-wedding-celebrations.jpg" width="300" height="250">&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://www.thebrewery.co.uk/wp-content/uploads/2023/10/154__Quickbooks_GetTogether2023-scaled.jpg"width="300" height="250">
<h2>UPCOMING EVENTS :--</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>